sudo: required
services:
  - docker

before_install:
  - docker build -t radosnydzwon/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true radosnydzwon/udemy-docker-react npm run test
